[package]
authors = ["Alexey Arbuzov <lexx.vir@gmail.com>"]
description = "BER-TLV parsing & emitting library"
documentation = "https://lexxvir.github.io/tlv-parser"
keywords = ["tlv"]
license = "MIT/Apache-2.0"
name = "tlv_parser"
readme = "README.md"
repository = "https://github.com/lexxvir/tlv-parser"
version = "0.1.4"

[dependencies]
byteorder = "^0"
error-chain = "^0"
rustc-serialize = "^0"

[dev-dependencies]
quickcheck = "0.3"
