[package]

name = "tlv_parser"
version = "0.0.2"
authors = ["Alexey Arbuzov <lexx.vir@gmail.com>"]

description = "BER-TLV parsing & emitting library"
repository = "https://github.com/lexxvir/tlv-parser"
documentation = "https://lexxvir.github.io/tlv-parser"
readme = "README.md"
keywords = ["tlv"]
license = "MIT/Apache-2.0"

[dependencies]
rustc-serialize = "^0"
byteorder = "^0"
error-chain = "^0"
